import type { SkillCandidate } from "./types";

/**
 * Curated fallback set of well-known Claude / AI-agent skills. Used only when
 * every live source fails (e.g. offline build) so the board is never empty.
 * Star counts are approximate snapshots and exist purely to seed an ordering;
 * live data always overrides this once a source responds.
 */
export const SEED_CANDIDATES: SkillCandidate[] = [
  {
    key: "gh:anthropics/skills",
    name: "skills",
    owner: "anthropics",
    description:
      "Official collection of Agent Skills for Claude — composable folders of instructions, scripts, and resources.",
    url: "https://github.com/anthropics/skills",
    kind: "skill",
    tags: ["claude", "agent-skills", "anthropic"],
    signals: { stars: 3800, forks: 420, daysSinceUpdate: 3, hnPoints: 210, mentions: 2 },
  },
  {
    key: "gh:anthropics/claude-code",
    name: "claude-code",
    owner: "anthropics",
    description: "Claude Code — Anthropic's agentic coding tool that lives in your terminal.",
    url: "https://github.com/anthropics/claude-code",
    kind: "repo",
    tags: ["claude-code", "cli", "agent"],
    signals: { stars: 31000, forks: 2100, daysSinceUpdate: 1, hnPoints: 540, mentions: 4 },
  },
  {
    key: "gh:modelcontextprotocol/servers",
    name: "servers",
    owner: "modelcontextprotocol",
    description: "Reference MCP servers — the most widely used tool integrations for agents.",
    url: "https://github.com/modelcontextprotocol/servers",
    kind: "repo",
    tags: ["mcp-server", "mcp", "tools"],
    signals: { stars: 24000, forks: 2600, daysSinceUpdate: 2, hnPoints: 320, mentions: 3 },
  },
  {
    key: "gh:hesreallyhim/awesome-claude-code",
    name: "awesome-claude-code",
    owner: "hesreallyhim",
    description: "A curated list of slash-commands, CLAUDE.md files, skills, and workflows for Claude Code.",
    url: "https://github.com/hesreallyhim/awesome-claude-code",
    kind: "repo",
    tags: ["claude-code", "awesome", "skills"],
    signals: { stars: 6200, forks: 410, daysSinceUpdate: 2, hnPoints: 90, mentions: 1 },
  },
  {
    key: "gh:punkpeye/awesome-mcp-servers",
    name: "awesome-mcp-servers",
    owner: "punkpeye",
    description: "A collection of MCP servers for connecting agents to data sources and tools.",
    url: "https://github.com/punkpeye/awesome-mcp-servers",
    kind: "repo",
    tags: ["mcp-server", "awesome", "mcp"],
    signals: { stars: 52000, forks: 4100, daysSinceUpdate: 1, hnPoints: 410, mentions: 3 },
  },
  {
    key: "gh:wshobson/agents",
    name: "agents",
    owner: "wshobson",
    description: "A collection of production-ready subagents for Claude Code.",
    url: "https://github.com/wshobson/agents",
    kind: "skill",
    tags: ["claude-code", "subagents", "agent"],
    signals: { stars: 9800, forks: 980, daysSinceUpdate: 2, hnPoints: 60, mentions: 1 },
  },
  {
    key: "gh:davila7/claude-code-templates",
    name: "claude-code-templates",
    owner: "davila7",
    description: "CLI to configure and monitor Claude Code — templates, agents, commands, and MCPs.",
    url: "https://github.com/davila7/claude-code-templates",
    kind: "repo",
    tags: ["claude-code", "templates", "cli"],
    signals: { stars: 7100, forks: 720, daysSinceUpdate: 1, weeklyDownloads: 18000, hnPoints: 40, mentions: 1 },
  },
  {
    key: "gh:anthropics/anthropic-cookbook",
    name: "anthropic-cookbook",
    owner: "anthropics",
    description: "Recipes and example code for building with Claude, including tool use and agents.",
    url: "https://github.com/anthropics/anthropic-cookbook",
    kind: "repo",
    tags: ["claude", "cookbook", "examples"],
    signals: { stars: 16000, forks: 1700, daysSinceUpdate: 6, hnPoints: 120, mentions: 1 },
  },
  {
    key: "gh:getAsterisk/claudia",
    name: "claudia",
    owner: "getAsterisk",
    description: "A GUI toolkit for Claude Code — custom agents, session management, and usage analytics.",
    url: "https://github.com/getAsterisk/claudia",
    kind: "repo",
    tags: ["claude-code", "gui", "agent"],
    signals: { stars: 11000, forks: 760, daysSinceUpdate: 4, hnPoints: 230, mentions: 2 },
  },
  {
    key: "gh:eyaltoledano/claude-task-master",
    name: "claude-task-master",
    owner: "eyaltoledano",
    description: "An AI task-management system you can drop into Claude Code and other agents.",
    url: "https://github.com/eyaltoledano/claude-task-master",
    kind: "repo",
    tags: ["claude-code", "tasks", "mcp-server"],
    signals: { stars: 14000, forks: 1300, daysSinceUpdate: 1, weeklyDownloads: 42000, hnPoints: 150, mentions: 2 },
  },
  {
    key: "gh:steipete/claude-code-mcp",
    name: "claude-code-mcp",
    owner: "steipete",
    description: "Run Claude Code as a one-shot MCP server so other agents can call it as a tool.",
    url: "https://github.com/steipete/claude-code-mcp",
    kind: "repo",
    tags: ["claude-code", "mcp-server"],
    signals: { stars: 1200, forks: 110, daysSinceUpdate: 9, weeklyDownloads: 5400, hnPoints: 30, mentions: 1 },
  },
  {
    key: "gh:contains-studio/agents",
    name: "agents",
    owner: "contains-studio",
    description: "Department-style subagents for Claude Code covering design, engineering, and marketing.",
    url: "https://github.com/contains-studio/agents",
    kind: "skill",
    tags: ["claude-code", "subagents", "skills"],
    signals: { stars: 5300, forks: 640, daysSinceUpdate: 5, hnPoints: 25, mentions: 1 },
  },
];
